#!/bin/sh

name=syncthing
org=derekschaefer
version=0.10.13
url=https://github.com/syncthing/syncthing/releases/download
dist=syncthing-linux-amd64-v$version

function clean() {
  rm -rf dist config sync
}

function download() {
  clean
  mkdir -p dist
  curl -O dist/$name.tar.gz $url/v$version/$dist.tar.gz
  tar -xzf dist/$name.tar.gz -C dist
  cp dist/$dist/syncthing dist
}

function build() {
  download
  docker build -t $org/$name .
}

function push() {
  build
  docker push $org/$name
}

for cmd in ${@:1}; do
  eval $cmd
done
