#!/bin/sh

NAME=syncthing
ORG=derekschaefer
VERSION=0.10.23
URL=https://github.com/syncthing/syncthing/releases/download
DIST=syncthing-linux-amd64-v$VERSION

function clean() {
  rm -rf dist config sync
}

function download() {
  mkdir -p dist
  curl -Lo dist/$NAME.tar.gz $URL/v$VERSION/$DIST.tar.gz
  tar -xzf dist/$NAME.tar.gz -C dist
  cp dist/$DIST/syncthing dist
}

function build() {
  docker build -t $ORG/$NAME .
}

function push() {
  docker push $ORG/$NAME
}

function all() {
  clean
  download
  build
}

for cmd in ${@:1}; do
  eval $cmd
done
